/*
=========================================================
PLAYER DATABASE
=========================================================
Add new players by copying one object and changing values.
Do NOT publish a player's exact birth date on the public page.
Use gradYear instead.

"image" can be a URL (e.g. https://.../photo.jpg) or left blank.
If left blank, the card/profile will show the player's initials instead.
=========================================================
*/
const players = [
  {
    name: "Jacob Thomsen",
    gradYear: "2030",
    team: "WIA Surf U16 Boys Blue",
    position: "Forward",
    jersey: "17",
    gpa: "4.0",
    school: "Lewis Central High School",
    major: "Nursing",
    playerEmail: "jacob.thomsen@lewiscentral.org",
    phone: "712-827-0701",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Will Grudle",
    gradYear: "2030",
    team: "WIA Surf U16 Boys Black",
    position: "Midfield",
    jersey: "8",
    gpa: "4.0",
    school: "Lewis Central High School",
    major: "Undecided",
    playerEmail: "will.grudle@gmail.com",
    phone: "712-827-7192",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "images/will-grudle.jpg",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Andrew Shearer",
    gradYear: "2029",
    team: "WIA Surf U16 Boys Black",
    position: "Defender",
    jersey: "13",
    gpa: "4.0",
    school: "Treynor High School",
    major: "Business, Finance, Engineering, Economics, Architecture",
    playerEmail: "andrewshearer228@gmail.com",
    phone: "402-982-9800",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Eli Yochum",
    gradYear: "2029",
    team: "WIA Surf U16 Boys Black",
    position: "Forward",
    jersey: "17",
    gpa: "4.0",
    school: "Treynor High School",
    major: "Engineering, Criminal Justice",
    playerEmail: "eliwyochum@gmail.com",
    phone: "712-796-5834",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Luke Mortensen",
    gradYear: "2030",
    team: "WIA Surf U16 Boys Black",
    position: "Forward",
    jersey: "1",
    gpa: "4.0",
    school: "Lewis Central High School",
    major: "Pre-Med",
    playerEmail: "lukemortensen2012@gmail.com",
    phone: "712-310-4166",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "images/IMG_0949.jpeg",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Blake Aldrich",
    gradYear: "2029",
    team: "WIA Surf U16 Boys Black",
    position: "Goalkeeper",
    jersey: "0",
    gpa: "3.75",
    school: "Lewis Central High School",
    major: "Business",
    playerEmail: "baldrich51611@gmail.com",
    phone: "402-657-3690",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Payton Witte",
    gradYear: "2029",
    team: "WIA Surf U16 Boys Black",
    position: "Defender",
    jersey: "21",
    gpa: "3.99",
    school: "Logan Magnolia High School",
    major: "Kinesiology / Exercise Science, Health Sciences",
    playerEmail: "pwitte33@gmail.com",
    phone: "712-216-2007",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "images/IMG_0951.jpeg",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Lewis Miranda",
    gradYear: "2029",
    team: "WIA Surf U16 Boys Black",
    position: "Midfield",
    jersey: "24",
    gpa: "3.5",
    school: "Papillion La Vista High School",
    major: "Accounting, Finance, Marketing, Engineering, Communications, Mathematics",
    playerEmail: "mirandalewis336@gmail.com",
    phone: "530-250-0507",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Maksym Dovbii",
    gradYear: "2029",
    team: "WIA Surf U16 Boys Blue",
    position: "Forward",
    jersey: "16",
    gpa: "3.4",
    school: "Boyer Valley Community School District",
    major: "Business, Accounting, Finance, Marketing, Computer Science",
    playerEmail: "dovbijmaksim907@gmail.com",
    phone: "+1 712-216-0229",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Jeremy Tomas",
    gradYear: "2029",
    team: "WIA Surf U16 Boys Black",
    position: "Defender",
    jersey: "22",
    gpa: "3.375",
    school: "Omaha South High School",
    major: "Business, Accounting, Finance, Marketing, Engineering, Communications, Mathematics, Welding",
    playerEmail: "tomasjeremy58@gmail.com",
    phone: "402-320-4664",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Doolin Vaughan",
    gradYear: "2029",
    team: "WIA Surf U16 Boys Black",
    position: "Defender",
    jersey: "11",
    gpa: "4.0",
    school: "Harlan High School",
    major: "Undecided",
    playerEmail: "vdoolin1199@icloud.com",
    phone: "402-850-9666",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "images/IMG_0952.jpeg",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Ethan Michael",
    gradYear: "2029",
    team: "WIA Surf U16 Boys Black",
    position: "Forward",
    jersey: "7",
    gpa: "4.0",
    school: "Underwood High School",
    major: "STEM",
    playerEmail: "ethancmichael@icloud.com",
    phone: "712-561-0815",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Logan Benson",
    gradYear: "2030",
    team: "WIA Surf U16 Boys Blue",
    position: "Forward",
    jersey: "7",
    gpa: "3.4",
    school: "Thomas Jefferson High School",
    major: "Undecided",
    playerEmail: "Lmbenson124@gmail.com",
    phone: "712-355-0290",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Maximiliano Iniguez",
    gradYear: "2029",
    team: "WIA Surf U16 Boys Blue",
    position: "Forward",
    jersey: "20",
    gpa: "3.0",
    school: "Blair High School",
    major: "Undecided",
    playerEmail: "maxiniguez23@gmail.com",
    phone: "402-468-2332",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Camden McCord",
    gradYear: "2030",
    team: "WIA Surf U16 Boys Blue",
    position: "Defender",
    jersey: "12",
    gpa: "3.75",
    school: "Heartland Christian School",
    major: "Finance",
    playerEmail: "camdenmccord57@gmail.com",
    phone: "402-677-7129",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Cael Johnson",
    gradYear: "2030",
    team: "WIA Surf U16 Boys Blue",
    position: "Defender",
    jersey: "3",
    gpa: "3.86",
    school: "Heartland Christian School",
    major: "Business, Finance",
    playerEmail: "johnsoncael62@gmail.com",
    phone: "+1 402-990-8441",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Samuel Wise",
    gradYear: "2029",
    team: "WIA Surf U16 Boys Blue",
    position: "Midfield",
    jersey: "6",
    gpa: "3.95",
    school: "Treynor High School",
    major: "Undecided",
    playerEmail: "samueldwise471@gmail.com",
    phone: "712-310-6568",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Gilberto Rodr\u00edguez Aguilar",
    gradYear: "2030",
    team: "WIA Surf U16 Boys Blue",
    position: "Forward",
    jersey: "10",
    gpa: "4.0",
    school: "Thomas Jefferson High School",
    major: "Business, Engineering, Architecture",
    playerEmail: "gilrodriagui12@gmail.com",
    phone: "712-713-9334",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Joey Lane",
    gradYear: "2030",
    team: "WIA Surf U16 Boys Blue",
    position: "Midfield",
    jersey: "11",
    gpa: "3.7",
    school: "Lewis Central High School",
    major: "Business",
    playerEmail: "joeylane2512@outlook.com",
    phone: "712-314-4345",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Kasey Donner",
    gradYear: "2030",
    team: "WIA Surf U16 Boys Blue",
    position: "Midfield",
    jersey: "0",
    gpa: "4.0",
    school: "Lewis Central High School",
    major: "Computer Science",
    playerEmail: "kasey.donner@gmail.com",
    phone: "712-340-3216",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Briggs Barta",
    gradYear: "2030",
    team: "WIA Surf U16 Boys Blue",
    position: "Goalkeeper",
    jersey: "2",
    gpa: "3.7",
    school: "Lewis Central High School",
    major: "Undecided",
    playerEmail: "briggs.barta@gmail.com",
    phone: "712-266-6649",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Aaron Martinez",
    gradYear: "2030",
    team: "WIA Surf U16 Boys Blue",
    position: "Midfield",
    jersey: "13",
    gpa: "No GPA yet",
    school: "Thomas Jefferson High School",
    major: "Psychology",
    playerEmail: "aa.mb775@gmail.com",
    phone: "712-308-4231",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Oliver Carns",
    gradYear: "2030",
    team: "WIA Surf U16 Boys Blue",
    position: "Midfield",
    jersey: "21",
    gpa: "4.0",
    school: "Abraham Lincoln High School",
    major: "Undecided",
    playerEmail: "carnsoliver23@gmail.com",
    phone: "712-254-6104",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Jameson Parks",
    gradYear: "2030",
    team: "WIA Surf U16 Boys Blue",
    position: "Defender",
    jersey: "9",
    gpa: "3.7",
    school: "Thomas Jefferson High School",
    major: "Undecided",
    playerEmail: "parksjameson912@gmail.com",
    phone: "402-981-9158",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Giovani Contreras Andrade",
    gradYear: "2029",
    team: "WIA Surf U16 Boys Black",
    position: "Defender",
    jersey: "26",
    gpa: "3.0",
    school: "Thomas Jefferson High School",
    major: "Undecided",
    playerEmail: "3cgio11@gmail.com",
    phone: "712-314-1415",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Jesus Salazar",
    gradYear: "2029",
    team: "WIA Surf U16 Boys Black",
    position: "Midfield",
    jersey: "36",
    gpa: "3.7",
    school: "Lewis Central High School",
    major: "Accounting",
    playerEmail: "j9058993@gmail.com",
    phone: "402-202-3984",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Eduardo Aguilar",
    gradYear: "2030",
    team: "WIA Surf U16 Boys Black",
    position: "Midfield",
    jersey: "27",
    gpa: "4.0",
    school: "Thomas Jefferson High School",
    major: "Marketing",
    playerEmail: "Lalinaguilar@icloud.com",
    phone: "402-401-1839",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  },
  {
    name: "Oliver Vides Gomez",
    gradYear: "2029",
    team: "WIA Surf U16 Boys Black",
    position: "Midfield",
    jersey: "10",
    gpa: "4.2",
    school: "Lewis Central High School",
    major: "Business",
    playerEmail: "olivervides10@gmail.com",
    phone: "239-223-8810",
    coach: "Ryan Grudle",
    coachEmail: "rgrudle@westerniowasurf.com",
    film: "",
    image: "",
    bio: "Add player bio here — playing style, strengths, leadership, development focus, and goals."
  }
];
